[hooks]
dynamic_quotes = 10
collections-import-rewrite = 20
reformat-generics = 40
noqa-reformat = 60
ellipsis-reformat = 70
squish_stubs = 80

[hooks.yapf]
priority = 30

[hooks.yapf.kwargs]
yapf_style = ".style.yapf"

[hooks.isort]
priority = 50

[hooks.isort.kwargs]
indent = "		"
multi_line_output = 8
import_heading_stdlib = "stdlib"
import_heading_thirdparty = "3rd party"
import_heading_firstparty = "this package"
import_heading_localfolder = "this package"
balanced_wrapping = false
lines_between_types = 0
use_parentheses = true
remove_redundant_aliases = true
default_section = "THIRDPARTY"
known_third_party = [
    "aenum",
    "alabaster",
    "beautifulsoup4",
    "bs4",
    "coincidence",
    "coverage",
    "coverage_pyver_pragma",
    "defusedxml",
    "domdf_python_tools",
    "extras_require",
    "github",
    "html5lib",
    "importlib_metadata",
    "pygments",
    "pytest",
    "pytest_cov",
    "pytest_randomly",
    "pytest_regressions",
    "pytest_rerunfailures",
    "pytest_timeout",
    "requests",
    "sphinx",
    "sphinx_autodoc_typehints",
    "sphinx_notfound_page",
    "sphinx_prompt",
    "sphinx_rtd_theme",
    "sphinx_tabs",
    "sphinx_toolbox",
    "sphinxcontrib_applehelp",
    "sphinxcontrib_devhelp",
    "sphinxcontrib_htmlhelp",
    "sphinxcontrib_httpdomain",
    "sphinxcontrib_jsmath",
    "sphinxcontrib_qthelp",
    "sphinxcontrib_serializinghtml",
    "sphinxemoji",
    "typing_extensions",
]
known_first_party = [ "enum_tools",]

[config]
indent = "	"
line_length = 115
